### ISSUE TITLE
:todo

### ISSUE THREAD

**Issue by atherdon** [atherdon/house-lp#51]
- [x] Email validation
- [x] Шрифты включить
- [x] Вырезать favicon
- [x] 3 modals test with different types of form validation
- [x] test validation
- [x] hover on header
- [x] fixed header
- [x] modals with validation has messages
- [x] убрать navbar default background для nav-links

- [x] убрать display none с modal error
- [x] исправить footer
- [ ] вырезать недостающие картинки и импортировать их в svg?

**Comment by atherdon** [comment]
http://jsfiddle.net/9Y7Cm/5/
![image](https://user-images.githubusercontent.com/1469198/28823633-3811eec8-76c7-11e7-8d44-116cef894fcf.png)

- [x] fix

**Comment by atherdon** [comment]
- [ ] вырезать недостающие картинки и импортировать их в svg?
